// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for fuchsia.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPRptZXBum6K_NdaTF5alei7Z9H55kIfg',
    appId: '1:899177334428:android:01ca7ba7fc513e69b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4GCdn77Z79Z7lxkNbaUImu7iVYGDBSw4',
    appId: '1:899177334428:ios:91b02f222e70d5a1b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
    androidClientId:
        '899177334428-87dmvgp8mcha8bkr0p3r7iq0isr7bjfo.apps'
        '.googleusercontent.com',
    iosClientId:
        '899177334428-6u0v3t7apkn0atkmfi55ht03bbu06s4i.apps'
        '.googleusercontent.com',
    iosBundleId: 'leadership.parkroadfellowship.org',
  );
}
