// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for fuchsia.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPRptZXBum6K_NdaTF5alei7Z9H55kIfg',
    appId: '1:899177334428:android:01ca7ba7fc513e69b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4GCdn77Z79Z7lxkNbaUImu7iVYGDBSw4',
    appId: '1:899177334428:ios:91b02f222e70d5a1b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
    androidClientId:
        '899177334428-87dmvgp8mcha8bkr0p3r7iq0isr7bjfo.apps.googleusercontent.com',
    iosClientId:
        '899177334428-6u0v3t7apkn0atkmfi55ht03bbu06s4i.apps.googleusercontent.com',
    iosBundleId: 'leadership.parkroadfellowship.org',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6A7EgDkjbV3a0olvtBmB1BvC24svSrsk',
    appId: '1:899177334428:web:47ced23ded66506eb18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    authDomain: 'parkroad-fellowship.firebaseapp.com',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
    measurementId: 'G-9QJT4TGNEN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4GCdn77Z79Z7lxkNbaUImu7iVYGDBSw4',
    appId: '1:899177334428:ios:68d95725c1cca395b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
    androidClientId:
        '899177334428-87dmvgp8mcha8bkr0p3r7iq0isr7bjfo.apps.googleusercontent.com',
    iosClientId:
        '899177334428-umroi5p4um5f44ksmg6tbl0l73soontr.apps.googleusercontent.com',
    iosBundleId: 'org.parkroadfellowship.leadership',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6A7EgDkjbV3a0olvtBmB1BvC24svSrsk',
    appId: '1:899177334428:web:47ced23ded66506eb18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    authDomain: 'parkroad-fellowship.firebaseapp.com',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
    measurementId: 'G-9QJT4TGNEN',
  );
}
