// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPRptZXBum6K_NdaTF5alei7Z9H55kIfg',
    appId: '1:899177334428:android:01ca7ba7fc513e69b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4GCdn77Z79Z7lxkNbaUImu7iVYGDBSw4',
    appId: '1:899177334428:ios:30e15ac8768e8d40b18f59',
    messagingSenderId: '899177334428',
    projectId: 'parkroad-fellowship',
    storageBucket: 'parkroad-fellowship.firebasestorage.app',
    androidClientId:
        '899177334428-f5s6jicejvusrm5clppm2lkt81fmo41b.apps.googleusercontent.com',
    iosClientId:
        '899177334428-umroi5p4um5f44ksmg6tbl0l73soontr.apps.googleusercontent.com',
    iosBundleId: 'org.parkroadfellowship.leadership',
  );
}
